### ISSUE TITLE
Example page not working

### ISSUE THREAD

**Issue by VitruxPT** [yuche/vue-strap#317]
I've been having the Example page open for some days now checking everything and today the all examples suddenly stopped working. 
I've tried it on another browser but it still doesn't work.

I can see the following error in the console:
`Uncaught TypeError: Cannot read property 'months' of undefined                           Datepicker.vue:229`

(Edit: I'm talking about this page: http://yuche.github.io/vue-strap/)

**Comment by wffranco** [comment]
Clean cache or something, that error was only yesterday because I moved the translations, was corrected last night.

**Comment by VitruxPT** [comment]
@wffranco I tried to clean cache, i tried in incognito mode (no cookies, cache, etc..) and tried in another browser and it still doesn't work.

**Comment by ZeoKnight** [comment]
Can confirm same error as @VitruxPT, cleared cache and tried via incognito as well

**Comment by santigarcor** [comment]
@wffranco I can confirm it too, the examples aren't working.

**Comment by wffranco** [comment]
I separate the language translations yesterday, so maybe you got that error while I was fixing it.

**Comment by VitruxPT** [comment]
@wffranco I'm getting the error now, not yesterday. It still doesn't work

**Comment by marceloch2** [comment]
Same here, my console.log show a error too

Datepicker.vue:296 Uncaught TypeError: Cannot read property 'months' of undefined

**Comment by marceloch2** [comment]
I fix my cloned vue-strap locally.

1) npm install style-loader ( Error happening trying to find this module );
2) And a dirty try catch in datepicker error;

This line bellow.

`return this.text.months[date.getMonth()]`

The .text is undefine.

**Comment by marceloch2** [comment]
Well, removed the try catch mentioned above and the problem is with translations(this.lang), inside vue-strap-lang.js i change the "en" key to "en-US"

```
'en-US': {
                daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
                limit: 'Limit reached ({{limit}} items max).',
                loading: 'Loading...',
                minLength: 'Min. Length',
                months: [
                    'January', 'February', 'March', 'April', 'May', 'June',
                    'July', 'August', 'September', 'October', 'November', 'December'
                ],
                notSelected: 'Nothing Selected',
                required: 'Required',
                search: 'Search'
            }
```

and 

```
var tr = {};
        for (var i in l['en-US']) {
            tr[i] = l[lang][i] || l['en-US'][i];
        }
        return tr;
```

all components working also the datepicker.

**Comment by wffranco** [comment]
@VitruxPT like I said when I edit, I test in some browsers and all fine (with my default language), just got the error in firefox, so I detect the error later.

Problem fixed. Sorry for the delay, solving other bugs and had some problems merging branches.

Greeting.
