### ISSUE TITLE
Bs-input with Popover triggered on focus not working

### ISSUE THREAD

**Issue by jankincl** [yuche/vue-strap#325]
I use bs-input within a popover tag, but the trigger="focus" doesn't work there. Only "hover" or "click". Is there a way to get the focus trigger work, like with normal input?

Thanks!

**Comment by jankincl** [comment]
Anyone has a solution to enable "focus" trigger for a popover with bs-input inside? Would appreciate any suggestions! Thanks.

**Comment by wffranco** [comment]
Fixed.

Greeting.

**Comment by jankincl** [comment]
Thanks, but when I tried it it still doesn't seem to work even in v1.1.20 . I use it like this:

`<popover title="Title" content="Lorem ipsum dolor" placement="left" trigger="focus" effect="fade" >
                        <bs-input :value.sync="models.name1" label="Report title" maxlength="40"></bs-input>
                    </popover>`

**Comment by wffranco** [comment]
In the documentation work right, I use it that way:
```html
<popover effect="scale" title="Title" content="Lorem ipsum dolor sit amet" placement="bottom" trigger="focus">
  <bs-input type="text" placeholder="Focus"></bs-input>
</popover>
<tooltip effect="scale" content="Lorem ipsum dolor sit amet" placement="bottom" trigger="focus">
  <bs-input type="text" placeholder="Focus"></bs-input>
</tooltip>
```
Are you sure you add the components?
Check if you have any error, or problem with your data...
Your example looks right, no idea what can be the problem.

**Comment by jankincl** [comment]
Thanks. Now it works for some reason, maybe it was problem with cache or something. Thanks for the update!
